/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CreateBrandDto
 */
export interface CreateBrandDto {
    /**
     * 
     * @type {string}
     * @memberof CreateBrandDto
     */
    businessId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBrandDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBrandDto
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBrandDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBrandDto
     */
    logoUrl?: string;
}

/**
 * Check if a given object implements the CreateBrandDto interface.
 */
export function instanceOfCreateBrandDto(value: object): value is CreateBrandDto {
    if (!('businessId' in value) || value['businessId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateBrandDtoFromJSON(json: any): CreateBrandDto {
    return CreateBrandDtoFromJSONTyped(json, false);
}

export function CreateBrandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBrandDto {
    if (json == null) {
        return json;
    }
    return {
        
        'businessId': json['businessId'],
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
    };
}

export function CreateBrandDtoToJSON(json: any): CreateBrandDto {
    return CreateBrandDtoToJSONTyped(json, false);
}

export function CreateBrandDtoToJSONTyped(value?: CreateBrandDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'businessId': value['businessId'],
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'logoUrl': value['logoUrl'],
    };
}

