/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CreateOrderItemDto
 */
export interface CreateOrderItemDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderItemDto
     */
    orderId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderItemDto
     */
    productId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateOrderItemDto
     */
    qty: number;
    /**
     * 
     * @type {number}
     * @memberof CreateOrderItemDto
     */
    price: number;
}

/**
 * Check if a given object implements the CreateOrderItemDto interface.
 */
export function instanceOfCreateOrderItemDto(value: object): value is CreateOrderItemDto {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('qty' in value) || value['qty'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function CreateOrderItemDtoFromJSON(json: any): CreateOrderItemDto {
    return CreateOrderItemDtoFromJSONTyped(json, false);
}

export function CreateOrderItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'productId': json['productId'],
        'qty': json['qty'],
        'price': json['price'],
    };
}

export function CreateOrderItemDtoToJSON(json: any): CreateOrderItemDto {
    return CreateOrderItemDtoToJSONTyped(json, false);
}

export function CreateOrderItemDtoToJSONTyped(value?: CreateOrderItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'productId': value['productId'],
        'qty': value['qty'],
        'price': value['price'],
    };
}

