/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CreateCategoryDto
 */
export interface CreateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    parentId?: string;
}

/**
 * Check if a given object implements the CreateCategoryDto interface.
 */
export function instanceOfCreateCategoryDto(value: object): value is CreateCategoryDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateCategoryDtoFromJSON(json: any): CreateCategoryDto {
    return CreateCategoryDtoFromJSONTyped(json, false);
}

export function CreateCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
    };
}

export function CreateCategoryDtoToJSON(json: any): CreateCategoryDto {
    return CreateCategoryDtoToJSONTyped(json, false);
}

export function CreateCategoryDtoToJSONTyped(value?: CreateCategoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'parentId': value['parentId'],
    };
}

