/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CreateOrderDto
 */
export interface CreateOrderDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderDto
     */
    supplierId: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateOrderDto
     */
    expectedDate: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderDto
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof CreateOrderDto
     */
    totalAmount: number;
}

/**
 * Check if a given object implements the CreateOrderDto interface.
 */
export function instanceOfCreateOrderDto(value: object): value is CreateOrderDto {
    if (!('supplierId' in value) || value['supplierId'] === undefined) return false;
    if (!('expectedDate' in value) || value['expectedDate'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('totalAmount' in value) || value['totalAmount'] === undefined) return false;
    return true;
}

export function CreateOrderDtoFromJSON(json: any): CreateOrderDto {
    return CreateOrderDtoFromJSONTyped(json, false);
}

export function CreateOrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'supplierId': json['supplierId'],
        'expectedDate': (new Date(json['expectedDate'])),
        'status': json['status'],
        'totalAmount': json['totalAmount'],
    };
}

export function CreateOrderDtoToJSON(json: any): CreateOrderDto {
    return CreateOrderDtoToJSONTyped(json, false);
}

export function CreateOrderDtoToJSONTyped(value?: CreateOrderDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'supplierId': value['supplierId'],
        'expectedDate': value['expectedDate'].toISOString(),
        'status': value['status'],
        'totalAmount': value['totalAmount'],
    };
}

