/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CreateTaxDto
 */
export interface CreateTaxDto {
    /**
     * 
     * @type {string}
     * @memberof CreateTaxDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTaxDto
     */
    rate: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTaxDto
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateTaxDto
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the CreateTaxDto interface.
 */
export function instanceOfCreateTaxDto(value: object): value is CreateTaxDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('rate' in value) || value['rate'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function CreateTaxDtoFromJSON(json: any): CreateTaxDto {
    return CreateTaxDtoFromJSONTyped(json, false);
}

export function CreateTaxDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaxDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'rate': json['rate'],
        'type': json['type'],
        'isActive': json['isActive'],
    };
}

export function CreateTaxDtoToJSON(json: any): CreateTaxDto {
    return CreateTaxDtoToJSONTyped(json, false);
}

export function CreateTaxDtoToJSONTyped(value?: CreateTaxDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'rate': value['rate'],
        'type': value['type'],
        'isActive': value['isActive'],
    };
}

