/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CreateSupplierDto
 */
export interface CreateSupplierDto {
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    contact: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    description: string;
}

/**
 * Check if a given object implements the CreateSupplierDto interface.
 */
export function instanceOfCreateSupplierDto(value: object): value is CreateSupplierDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('contact' in value) || value['contact'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateSupplierDtoFromJSON(json: any): CreateSupplierDto {
    return CreateSupplierDtoFromJSONTyped(json, false);
}

export function CreateSupplierDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSupplierDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'contact': json['contact'],
        'description': json['description'],
    };
}

export function CreateSupplierDtoToJSON(json: any): CreateSupplierDto {
    return CreateSupplierDtoToJSONTyped(json, false);
}

export function CreateSupplierDtoToJSONTyped(value?: CreateSupplierDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'contact': value['contact'],
        'description': value['description'],
    };
}

