/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CreateProductDto
 */
export interface CreateProductDto {
    /**
     * 
     * @type {string}
     * @memberof CreateProductDto
     */
    supplierId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductDto
     */
    sku: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProductDto
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateProductDto
     */
    stockQty?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateProductDto
     */
    brandId?: string;
    /**
     * 
     * @type {object}
     * @memberof CreateProductDto
     */
    metadata?: object;
}

/**
 * Check if a given object implements the CreateProductDto interface.
 */
export function instanceOfCreateProductDto(value: object): value is CreateProductDto {
    if (!('supplierId' in value) || value['supplierId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sku' in value) || value['sku'] === undefined) return false;
    return true;
}

export function CreateProductDtoFromJSON(json: any): CreateProductDto {
    return CreateProductDtoFromJSONTyped(json, false);
}

export function CreateProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductDto {
    if (json == null) {
        return json;
    }
    return {
        
        'supplierId': json['supplierId'],
        'name': json['name'],
        'sku': json['sku'],
        'price': json['price'] == null ? undefined : json['price'],
        'stockQty': json['stockQty'] == null ? undefined : json['stockQty'],
        'brandId': json['brandId'] == null ? undefined : json['brandId'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateProductDtoToJSON(json: any): CreateProductDto {
    return CreateProductDtoToJSONTyped(json, false);
}

export function CreateProductDtoToJSONTyped(value?: CreateProductDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'supplierId': value['supplierId'],
        'name': value['name'],
        'sku': value['sku'],
        'price': value['price'],
        'stockQty': value['stockQty'],
        'brandId': value['brandId'],
        'metadata': value['metadata'],
    };
}

