/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CreateOrganizationDto
 */
export interface CreateOrganizationDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationDto
     */
    businessType: CreateOrganizationDtoBusinessTypeEnum;
}


/**
 * @export
 */
export const CreateOrganizationDtoBusinessTypeEnum = {
    Retail: 'retail',
    Service: 'service',
    Manufacturing: 'manufacturing'
} as const;
export type CreateOrganizationDtoBusinessTypeEnum = typeof CreateOrganizationDtoBusinessTypeEnum[keyof typeof CreateOrganizationDtoBusinessTypeEnum];


/**
 * Check if a given object implements the CreateOrganizationDto interface.
 */
export function instanceOfCreateOrganizationDto(value: object): value is CreateOrganizationDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('businessType' in value) || value['businessType'] === undefined) return false;
    return true;
}

export function CreateOrganizationDtoFromJSON(json: any): CreateOrganizationDto {
    return CreateOrganizationDtoFromJSONTyped(json, false);
}

export function CreateOrganizationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'businessType': json['businessType'],
    };
}

export function CreateOrganizationDtoToJSON(json: any): CreateOrganizationDto {
    return CreateOrganizationDtoToJSONTyped(json, false);
}

export function CreateOrganizationDtoToJSONTyped(value?: CreateOrganizationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'businessType': value['businessType'],
    };
}

