/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CreateDiscountDto
 */
export interface CreateDiscountDto {
    /**
     * 
     * @type {string}
     * @memberof CreateDiscountDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDiscountDto
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDiscountDto
     */
    type: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateDiscountDto
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateDiscountDto
     */
    end: Date;
    /**
     * 
     * @type {boolean}
     * @memberof CreateDiscountDto
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the CreateDiscountDto interface.
 */
export function instanceOfCreateDiscountDto(value: object): value is CreateDiscountDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function CreateDiscountDtoFromJSON(json: any): CreateDiscountDto {
    return CreateDiscountDtoFromJSONTyped(json, false);
}

export function CreateDiscountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDiscountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
        'type': json['type'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'isActive': json['isActive'],
    };
}

export function CreateDiscountDtoToJSON(json: any): CreateDiscountDto {
    return CreateDiscountDtoToJSONTyped(json, false);
}

export function CreateDiscountDtoToJSONTyped(value?: CreateDiscountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
        'type': value['type'],
        'start': value['start'].toISOString(),
        'end': value['end'].toISOString(),
        'isActive': value['isActive'],
    };
}

