/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface InviteUserDto
 */
export interface InviteUserDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof InviteUserDto
     */
    emails: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof InviteUserDto
     */
    role?: InviteUserDtoRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof InviteUserDto
     */
    inviterUserId: string;
    /**
     * 
     * @type {string}
     * @memberof InviteUserDto
     */
    orgId: string;
}


/**
 * @export
 */
export const InviteUserDtoRoleEnum = {
    OrgAdmin: 'org:admin',
    OrgMember: 'org:member'
} as const;
export type InviteUserDtoRoleEnum = typeof InviteUserDtoRoleEnum[keyof typeof InviteUserDtoRoleEnum];


/**
 * Check if a given object implements the InviteUserDto interface.
 */
export function instanceOfInviteUserDto(value: object): value is InviteUserDto {
    if (!('emails' in value) || value['emails'] === undefined) return false;
    if (!('inviterUserId' in value) || value['inviterUserId'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    return true;
}

export function InviteUserDtoFromJSON(json: any): InviteUserDto {
    return InviteUserDtoFromJSONTyped(json, false);
}

export function InviteUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'emails': json['emails'],
        'role': json['role'] == null ? undefined : json['role'],
        'inviterUserId': json['inviterUserId'],
        'orgId': json['orgId'],
    };
}

export function InviteUserDtoToJSON(json: any): InviteUserDto {
    return InviteUserDtoToJSONTyped(json, false);
}

export function InviteUserDtoToJSONTyped(value?: InviteUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emails': value['emails'],
        'role': value['role'],
        'inviterUserId': value['inviterUserId'],
        'orgId': value['orgId'],
    };
}

