/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface UpdateOrderItemDto
 */
export interface UpdateOrderItemDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateOrderItemDto
     */
    qty?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateOrderItemDto
     */
    price?: number;
}

/**
 * Check if a given object implements the UpdateOrderItemDto interface.
 */
export function instanceOfUpdateOrderItemDto(value: object): value is UpdateOrderItemDto {
    return true;
}

export function UpdateOrderItemDtoFromJSON(json: any): UpdateOrderItemDto {
    return UpdateOrderItemDtoFromJSONTyped(json, false);
}

export function UpdateOrderItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrderItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'qty': json['qty'] == null ? undefined : json['qty'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function UpdateOrderItemDtoToJSON(json: any): UpdateOrderItemDto {
    return UpdateOrderItemDtoToJSONTyped(json, false);
}

export function UpdateOrderItemDtoToJSONTyped(value?: UpdateOrderItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qty': value['qty'],
        'price': value['price'],
    };
}

