/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface UpdateBrandDto
 */
export interface UpdateBrandDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateBrandDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBrandDto
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBrandDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBrandDto
     */
    logoUrl?: string;
}

/**
 * Check if a given object implements the UpdateBrandDto interface.
 */
export function instanceOfUpdateBrandDto(value: object): value is UpdateBrandDto {
    return true;
}

export function UpdateBrandDtoFromJSON(json: any): UpdateBrandDto {
    return UpdateBrandDtoFromJSONTyped(json, false);
}

export function UpdateBrandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBrandDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'description': json['description'] == null ? undefined : json['description'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
    };
}

export function UpdateBrandDtoToJSON(json: any): UpdateBrandDto {
    return UpdateBrandDtoToJSONTyped(json, false);
}

export function UpdateBrandDtoToJSONTyped(value?: UpdateBrandDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'logoUrl': value['logoUrl'],
    };
}

