/* tslint:disable */
/* eslint-disable */
/**
 * Abc
 * aa
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface UpdateOrganizationDto
 */
export interface UpdateOrganizationDto {
    /**
     * 
     * @type {object}
     * @memberof UpdateOrganizationDto
     */
    name: object;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizationDto
     */
    businessType: UpdateOrganizationDtoBusinessTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof UpdateOrganizationDto
     */
    orgId: object;
}


/**
 * @export
 */
export const UpdateOrganizationDtoBusinessTypeEnum = {
    Retail: 'retail',
    Service: 'service',
    Manufacturing: 'manufacturing'
} as const;
export type UpdateOrganizationDtoBusinessTypeEnum = typeof UpdateOrganizationDtoBusinessTypeEnum[keyof typeof UpdateOrganizationDtoBusinessTypeEnum];


/**
 * Check if a given object implements the UpdateOrganizationDto interface.
 */
export function instanceOfUpdateOrganizationDto(value: object): value is UpdateOrganizationDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('businessType' in value) || value['businessType'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    return true;
}

export function UpdateOrganizationDtoFromJSON(json: any): UpdateOrganizationDto {
    return UpdateOrganizationDtoFromJSONTyped(json, false);
}

export function UpdateOrganizationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganizationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'businessType': json['businessType'],
        'orgId': json['orgId'],
    };
}

export function UpdateOrganizationDtoToJSON(json: any): UpdateOrganizationDto {
    return UpdateOrganizationDtoToJSONTyped(json, false);
}

export function UpdateOrganizationDtoToJSONTyped(value?: UpdateOrganizationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'businessType': value['businessType'],
        'orgId': value['orgId'],
    };
}

