/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface UpdateTaxDto
 */
export interface UpdateTaxDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTaxDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaxDto
     */
    rate?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaxDto
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTaxDto
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the UpdateTaxDto interface.
 */
export function instanceOfUpdateTaxDto(value: object): value is UpdateTaxDto {
    return true;
}

export function UpdateTaxDtoFromJSON(json: any): UpdateTaxDto {
    return UpdateTaxDtoFromJSONTyped(json, false);
}

export function UpdateTaxDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaxDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'rate': json['rate'] == null ? undefined : json['rate'],
        'type': json['type'] == null ? undefined : json['type'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function UpdateTaxDtoToJSON(json: any): UpdateTaxDto {
    return UpdateTaxDtoToJSONTyped(json, false);
}

export function UpdateTaxDtoToJSONTyped(value?: UpdateTaxDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'rate': value['rate'],
        'type': value['type'],
        'isActive': value['isActive'],
    };
}

