/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface UpdateCategoryDto
 */
export interface UpdateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    parentId?: string;
}

/**
 * Check if a given object implements the UpdateCategoryDto interface.
 */
export function instanceOfUpdateCategoryDto(value: object): value is UpdateCategoryDto {
    return true;
}

export function UpdateCategoryDtoFromJSON(json: any): UpdateCategoryDto {
    return UpdateCategoryDtoFromJSONTyped(json, false);
}

export function UpdateCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
    };
}

export function UpdateCategoryDtoToJSON(json: any): UpdateCategoryDto {
    return UpdateCategoryDtoToJSONTyped(json, false);
}

export function UpdateCategoryDtoToJSONTyped(value?: UpdateCategoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'parentId': value['parentId'],
    };
}

