/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface UpdateOrderDto
 */
export interface UpdateOrderDto {
    /**
     * 
     * @type {Date}
     * @memberof UpdateOrderDto
     */
    expectedDate: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrderDto
     */
    status: string;
}

/**
 * Check if a given object implements the UpdateOrderDto interface.
 */
export function instanceOfUpdateOrderDto(value: object): value is UpdateOrderDto {
    if (!('expectedDate' in value) || value['expectedDate'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UpdateOrderDtoFromJSON(json: any): UpdateOrderDto {
    return UpdateOrderDtoFromJSONTyped(json, false);
}

export function UpdateOrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'expectedDate': (new Date(json['expectedDate'])),
        'status': json['status'],
    };
}

export function UpdateOrderDtoToJSON(json: any): UpdateOrderDto {
    return UpdateOrderDtoToJSONTyped(json, false);
}

export function UpdateOrderDtoToJSONTyped(value?: UpdateOrderDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expectedDate': value['expectedDate'].toISOString(),
        'status': value['status'],
    };
}

