/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface UpdateDiscountDto
 */
export interface UpdateDiscountDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateDiscountDto
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateDiscountDto
     */
    value?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateDiscountDto
     */
    type?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateDiscountDto
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateDiscountDto
     */
    end?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateDiscountDto
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the UpdateDiscountDto interface.
 */
export function instanceOfUpdateDiscountDto(value: object): value is UpdateDiscountDto {
    return true;
}

export function UpdateDiscountDtoFromJSON(json: any): UpdateDiscountDto {
    return UpdateDiscountDtoFromJSONTyped(json, false);
}

export function UpdateDiscountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDiscountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'value': json['value'] == null ? undefined : json['value'],
        'type': json['type'] == null ? undefined : json['type'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function UpdateDiscountDtoToJSON(json: any): UpdateDiscountDto {
    return UpdateDiscountDtoToJSONTyped(json, false);
}

export function UpdateDiscountDtoToJSONTyped(value?: UpdateDiscountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
        'type': value['type'],
        'start': value['start'] == null ? value['start'] : value['start'].toISOString(),
        'end': value['end'] == null ? value['end'] : value['end'].toISOString(),
        'isActive': value['isActive'],
    };
}

