/* tslint:disable */
/* eslint-disable */
/**
 * Eclipso POS API
 * A comprehensive RESTful API for the Eclipso Point-of-Sale system. This API provides secure endpoints for authentication, multi-tenant organization management, user administration, and core business operations. Built with NestJS and designed for retail and hospitality environments, it supports real-time synchronization, role-based access control, and seamless third-party integrations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface UpdateProductDto
 */
export interface UpdateProductDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateProductDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductDto
     */
    sku?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductDto
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductDto
     */
    stockQty?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductDto
     */
    brandId?: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateProductDto
     */
    metadata?: object;
}

/**
 * Check if a given object implements the UpdateProductDto interface.
 */
export function instanceOfUpdateProductDto(value: object): value is UpdateProductDto {
    return true;
}

export function UpdateProductDtoFromJSON(json: any): UpdateProductDto {
    return UpdateProductDtoFromJSONTyped(json, false);
}

export function UpdateProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProductDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'price': json['price'] == null ? undefined : json['price'],
        'stockQty': json['stockQty'] == null ? undefined : json['stockQty'],
        'brandId': json['brandId'] == null ? undefined : json['brandId'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UpdateProductDtoToJSON(json: any): UpdateProductDto {
    return UpdateProductDtoToJSONTyped(json, false);
}

export function UpdateProductDtoToJSONTyped(value?: UpdateProductDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'sku': value['sku'],
        'price': value['price'],
        'stockQty': value['stockQty'],
        'brandId': value['brandId'],
        'metadata': value['metadata'],
    };
}

